language: ruby
rvm:
  - 2.0.0
before_script:
  - cd spec/dummy && RAILS_ENV=test bundle exec rake --trace db:migrate && cd ../..
  - cd spec/dummy && RAILS_ENV=test bundle exec rails generate fencepost_config && cd ../..
  - cd spec/dummy/config/initializers/ && cat fencepost.rb | grep -v "dob" > fencepost2.rb
  - cat fencepost2.rb | grep -v "person_id" > fencepost3.rb
  - mv fencepost3.rb fencepost.rb
  - cd ../..
script:
  - bundle exec rspec spec
