---
:address:
  :model: !ruby/class 'Address'
  :attributes:
  - :id
  # - :person_id
  - :address_line_1
  - :address_line_2
  - :city
  - :state_province
  - :postal_code
  :demodulized_name: :address
  :nested_collection_name: :addresses
  :nested_attributes_name: :addresses_attributes
  :nested_attributes_options:
    :address_type:
      :allow_destroy: false
      :update_only: false
  :nested_singular_name: :address_attributes
:address_type:
  :model: !ruby/class 'AddressType'
  :attributes:
  - :id
  - :key
  - :label
  :demodulized_name: :address_type
  :nested_collection_name: :address_types
  :nested_attributes_name: :address_types_attributes
  :nested_attributes_options: {}
  :nested_singular_name: :address_type_attributes
:person:
  :model: !ruby/class 'Person'
  :attributes:
  - :id
  - :first_name
  - :last_name
  # - :dob
  :demodulized_name: :person
  :nested_collection_name: :people
  :nested_attributes_name: :people_attributes
  :nested_attributes_options:
    :addresses:
      :allow_destroy: false
      :update_only: false
  :nested_singular_name: :person_attributes

